# temp stage
FROM python:3.10.0-slim as builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt update && \
    apt upgrade -y && \
    apt install -y --no-install-recommends gcc


RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ../requirements.txt .
RUN /opt/venv/bin/pip install --no-cache-dir --upgrade -r requirements.txt


# final stage
FROM python:3.10.6-alpine3.16

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

RUN addgroup --gid 1001 --system app && \
    adduser --no-create-home --shell /bin/false --disabled-password --uid 1001 --system app

USER app

WORKDIR /code
COPY ../app /code/app
WORKDIR /code
CMD ["gunicorn", "app.main:app", "-w 4", "-k uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:80"]
